Algoritmo "mostrarDados"
// Disciplina   : [Criação de Aplicações e Sistemas]
// Professor   : Franklin Portela
// Descrição   : Um algoritimo que mostra dados (informações) na tela
// Autor(a)    : Pedro Verner
// Data atual  : 27/09/2022
Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

Escreval("Nome: Pierre")
Escreval("Idade:", 20)
Escreval("Altura:", 1.78)
Escreval("Tem criança?", falso)

Fimalgoritmo